// 화면 문구(한국어). 코드에서는 키로만 참조한다. 다른 언어는 같은 키로 strings.<lang>.js를 추가한다.
(function (root) {
  root.KKUK = root.KKUK || {};
  root.KKUK.stringsByLang = root.KKUK.stringsByLang || {};
  root.KKUK.stringsByLang.ko = root.KKUK.strings = {
    langName: '한국어',
    title: '꾹!',
    tagline: '누르면 작아지고, 떼면 튀어 올라요',
    stepPress: '누르기', stepPressDetail: '몸을 압축',
    stepDrag: '드래그', stepDragDetail: '좌우로 이동',
    stepRelease: '떼기', stepReleaseDetail: '반동으로 팽창',
    start: '시작하기',
    startHint: '키보드: ← → / A D 이동 · 스페이스 압축',
    tutorialStart: '튜토리얼 시작',
    tutorialFirst: '처음이라면 1분 연습부터 해 보세요',
    skipTutorial: '건너뛰고 바로 시작',
    replayTutorial: '튜토리얼 다시 보기',
    quitTutorial: '연습 그만두기',
    home: '시작 화면',
    settings: '설정',
    pausedTitle: '잠깐 쉬어가기',
    pausedDetail: '돌아오면 같은 위치에서 계속합니다.',
    pausedHeld: '압축 상태도 그대로 보존됩니다.',
    pauseReason: {
      button: '', key: '', settings: '',
      blur: '다른 창으로 이동해 멈췄어요.',
      hidden: '화면이 가려져 멈췄어요.',
      pointercancel: '터치가 끊겨 멈췄어요. 반동은 적용되지 않았어요.',
      resize: '화면 크기가 바뀌어 멈췄어요.',
      stall: '화면이 잠시 멈춰서 일시정지했어요.',
      lag: '기기가 느려져 일시정지했어요.'
    },
    ready: '준비',
    readyHeld: '누르고 있으면 압축을 이어 가고, 떼고 있으면 반동이 나와요',
    readyFree: '잠시 후 다시 움직여요',
    resume: '계속하기',
    retry: '바로 다시 하기',
    newBest: '최고 기록 갱신',
    passedLabel: '통과',
    retryHint: '스페이스로 바로 재시작',
    mixedNote: '터치와 키보드를 함께 쓴 기록은 따로 저장돼요',
    mode: { touch: '터치', keyboard: '키보드', mixed: '혼합' },
    passedSummary: '{n}개의 틈을 통과했어요',
    best: '최고',
    bestScope: '이 기기에 저장된 기록',
    passedHud: '{n}개 통과',
    bestLine: '나의 최고 기록',
    pause: '일시정지',
    padIdle: '누른 채 좌우로 드래그',
    padHeld: '압축 중 · 좌우로 움직이세요',
    noteIdle: '키보드: ← → / A D 이동 · 스페이스 압축',
    notePlaying: '드래그로 틈에 맞추세요',
    energy: '압축 에너지',
    energyCharging: '압축 에너지 축적',
    energyReleasing: '몸을 펼쳐 에너지 방출',
    energyWarning: '압축 한계가 가까워요',
    gateShort: '짧게 꾹', gateLong: '길게 꾹', gateDouble: '연속 틈',
    reason: {
      overpressure: '너무 오래 눌렀어요. 넓은 곳에서 풀어 주세요.',
      misaligned: '틈의 위치와 어긋났어요. 좌우로 맞춰 보세요.',
      expanded_too_early: '아직 틈 안이에요. 조금 더 지난 뒤에 풀어 보세요.',
      insufficient_compression: '벽에 닿았어요. 틈에 닿기 전에 더 작아져야 해요.',
      unknown: '벽에 닿았어요.'
    },
    canvasLabel: '누른 채 좌우로 드래그해 생물을 이동하고 압축하여 틈을 통과하는 게임',

    // 성장 모드
    modeChallenge: '도전', modeChallengeDetail: '순수 실력 기록',
    modeGrowth: '성장', modeGrowthDetail: '구슬 · 능력 빌드',
    badgeNew: 'NEW',
    growthPrefix: '성장',
    level: 'Lv {n}',
    levelUpTitle: '레벨 업!',
    levelUpSub: '능력 하나를 고르세요 · 키보드 1 2 3',
    evolution: '진화', curse: '저주',
    stackOf: '{n}/{m}',
    picksTitle: '이번 빌드',
    shieldBroke: '보호막이 막았어요!',
    ability: {
      toughBody: { name: '단단한 몸', desc: '에너지가 {a}% 느리게 쌓여요' },
      quickRecover: { name: '빠른 회복', desc: '몸을 펼치면 에너지가 {a}% 빨리 빠져요' },
      cushion: { name: '탄성 쿠션', desc: '반동이 {a}% 작아져요' },
      shockwave: { name: '충격파', desc: '에너지 {a}% 이상에서 떼면 앞 벽의 틈이 +{b} 넓어져요' },
      slideFeet: { name: '미끄럼 발', desc: '좌우 이동 속도 +{a}%' },
      shield: { name: '보호막', desc: '벽에 한 번 부딪혀도 버텨요. 부딪힌 벽은 부서져요' },
      foresight: { name: '예지', desc: '화면 위 바깥의 틈 {a}개를 미리 보여 줘요' },
      focus: { name: '집중', desc: '에너지 {a}% 이상이면 상승 속도 ×{b}' },
      magnet: { name: '자석', desc: '구슬을 줍는 범위가 넓어져요' },
      steelLungs: { name: '강철 폐', desc: '과압축 한계가 {a}%로 늘어나요' },
      reboundBlast: { name: '반동 폭발', desc: '에너지 {a}% 이상에서 떼면 앞 벽 하나를 부숴요' },
      haste: { name: '가속의 저주', desc: '상승 속도 +{a}%, 구슬 경험치 ×{b}' }
    },

    zones: ['새벽', '하늘', '노을', '밤', '오로라'],
    speedUp: '속도 UP',
    modeDaily: '오늘', modeDailyDetail: '같은 코스 · 고스트',
    dailyBestShort: '최고 {n} m',
    dailyPrefix: '오늘',
    dailyTitle: '오늘의 도전',
    dailyBonus: '오늘 첫 완주 +{n} 별',
    attemptN: '{n}번째 도전',
    ghost: '고스트',
    // 친구 도전장
    challengeSend: '도전장 보내기', challengeBack: '되받아치기',
    challengeTitle: '도전장 보내기',
    nameLabel: '내 이름(선택)', namePlaceholder: '친구에게 보일 이름',
    shareMsg: '꾹!에서 {h} m 올라갔어. 같은 코스로 이겨 볼래?',
    shareBtn: '보내기', copyBtn: '링크 복사',
    copied: '링크를 복사했어요', shared: '보냈어요', shareFail: '복사하지 못했어요. 길게 눌러 직접 복사해 주세요',
    noGhostNote: '판이 길어 고스트 없이 기록만 보내요',
    localWarn: '지금 주소는 이 PC(같은 Wi-Fi)에서만 열려요. 친구에게 보내려면 게임을 공개 주소(https)에 올려야 해요.',
    incomingTitle: '도전장 도착!',
    incomingFrom: '{name}님의 기록', incomingFriend: '친구의 기록',
    statusVerified: '✓ 기록 확인됨', statusUnverified: '고스트 없음 · 기록 미확인', statusMismatch: '⚠ 기록이 맞지 않아요(조작 의심)',
    statusVersion: '다른 버전의 도전장이라 같은 코스를 만들 수 없어요',
    accept: '대결 시작', later: '나중에',
    badLink: '도전장 링크가 올바르지 않아요',
    win: '승리!', lose: '아쉽게 패배', draw: '무승부',
    vsLine: 'vs {name} {h} m', vsDiff: '{d} m 차이',
    rematch: '다시 대결', vsPrefix: '상대',
    nearMissPop: '아슬!', riskyPop: '배짱!',
    nearMissLabel: '아슬',
    missionsTitle: '미션', missionDone: '미션 완료',
    missions: {
      nearMiss: '아슬아슬 통과 {n}번', height: '한 판에 {n} m 도달', gates: '틈 {n}개 통과', double: '연속 틈 {n}번 통과',
      long: '긴 틈 {n}번 통과', risky: '에너지 85% 넘겨 떼고 버티기 {n}번', growthLevel: '성장 모드 Lv {n} 달성', runs: '{n}판 플레이'
    },
    skinsTitle: '외형',
    coinUnit: '별',
    equipped: '장착 중', equip: '장착',
    unlockFor: '{n} 별로 열기',
    needMore: '별 {n}개 더 필요',
    earned: '+{n} 별',
    coinsHint: '판이 끝날 때마다 통과 3개당 별 1개(한 판 최대 20). 외형은 모습만 바뀌고 판정은 같아요.',
    unlockBtn: '열기',
    skinNames: { base: '젤리', slime: '민트 슬라임', orange: '오렌지', watermelon: '수박', puffer: '복어', fur: '털뭉치', moon: '달', glass: '유리구슬' },
    practice: '연습',
    tutorial: {
      press: { title: '눌렀다 떼기', hint: '아무 곳이나 누르면 작아지고, 떼면 튀어 올라요. 두 번 해 보세요.' },
      drag: { title: '좌우로 맞추기', hint: '누른 채 좌우로 끌어 빛나는 영역에 잠시 머무르세요.' },
      gate: { title: '틈 통과하기', hint: '틈에 닿기 전에 눌러 작아지고, 완전히 지난 뒤에 떼세요.' },
      energy: { title: '에너지 다루기', hint: '오래 누르면 에너지가 쌓여요. {n}%를 넘긴 뒤 떼고, 에너지가 빠지는 걸 보세요.' },
      retry: '다시 해 볼게요',
      zone: '좋아요!',
      doneTitle: '준비 완료!',
      doneDetail: '이제 실제 도전이에요.\n연습은 기록에 남지 않아요.',
      skippedDetail: '튜토리얼은 설정에서 언제든 다시 볼 수 있어요.'
    },

    settingsTitle: '설정',
    sfx: '효과음',
    music: '음악', musicNone: '아직 음악 트랙이 없어요',
    haptics: '진동', hapticsNone: '이 기기는 진동을 지원하지 않아요',
    reducedEffects: '연출 줄이기', reducedEffectsDetail: '화면 흔들림·번쩍임·파티클을 끕니다',
    language: '언어',
    privacy: '개인정보 안내',
    privacyBody: '기록과 설정은 이 기기의 브라우저에만 저장됩니다. 계정, 광고, 분석, 서버 전송은 없습니다.',
    close: '닫기',
    on: '켜짐', off: '꺼짐'
  };
})(typeof globalThis !== 'undefined' ? globalThis : this);
