// UI strings (English). Same keys as strings.ko.js.
(function (root) {
  root.KKUK = root.KKUK || {};
  root.KKUK.stringsByLang = root.KKUK.stringsByLang || {};
  root.KKUK.stringsByLang.en = {
    langName: 'English',
    title: 'Boing!',
    tagline: 'Press to shrink. Let go to bounce back.',
    stepPress: 'Press', stepPressDetail: 'Squeeze',
    stepDrag: 'Drag', stepDragDetail: 'Move sideways',
    stepRelease: 'Release', stepReleaseDetail: 'Bounce out',
    start: 'Start',
    startHint: 'Keyboard: ← → / A D move · Space squeeze',
    tutorialStart: 'Start tutorial',
    tutorialFirst: 'New here? Try the 1-minute practice first.',
    skipTutorial: 'Skip and play',
    replayTutorial: 'Replay tutorial',
    quitTutorial: 'Quit practice',
    home: 'Home',
    settings: 'Settings',
    pausedTitle: 'Paused',
    pausedDetail: 'You will continue from the same spot.',
    pausedHeld: 'Your squeeze is kept as it was.',
    pauseReason: {
      button: '', key: '', settings: '',
      blur: 'Paused because you switched windows.',
      hidden: 'Paused because the screen was hidden.',
      pointercancel: 'Paused because the touch was interrupted. No bounce was applied.',
      resize: 'Paused because the screen size changed.',
      stall: 'Paused because the screen froze for a moment.',
      lag: 'Paused because the device slowed down.'
    },
    ready: 'Ready',
    readyHeld: 'Keep holding to stay squeezed, or let go to bounce',
    readyFree: 'Moving again in a moment',
    resume: 'Continue',
    retry: 'Play again',
    newBest: 'New best',
    passedLabel: 'Gaps',
    retryHint: 'Press Space to restart',
    mixedNote: 'Runs using both touch and keyboard are saved separately',
    mode: { touch: 'Touch', keyboard: 'Keyboard', mixed: 'Mixed' },
    passedSummary: 'You passed {n} gaps',
    best: 'best',
    bestScope: 'Records saved on this device',
    passedHud: '{n} passed',
    bestLine: 'My best',
    pause: 'Pause',
    padIdle: 'Hold and drag sideways',
    padHeld: 'Squeezing · move sideways',
    noteIdle: 'Keyboard: ← → / A D move · Space squeeze',
    notePlaying: 'Drag to line up with the gap',
    energy: 'Squeeze energy',
    energyCharging: 'Building energy',
    energyReleasing: 'Expanding, energy draining',
    energyWarning: 'Close to the limit',
    gateShort: 'Quick', gateLong: 'Long', gateDouble: 'Double',
    reason: {
      overpressure: 'You held too long. Let go in an open space.',
      misaligned: 'You were off the gap. Line up sideways.',
      expanded_too_early: 'Still inside the gap. Let go a little later.',
      insufficient_compression: 'You hit the wall. Get smaller before the gap.',
      unknown: 'You hit the wall.'
    },
    canvasLabel: 'Hold and drag to move and squeeze the creature through gaps',

    // Growth mode
    modeChallenge: 'Challenge', modeChallengeDetail: 'Pure skill',
    modeGrowth: 'Growth', modeGrowthDetail: 'Abilities',
    badgeNew: 'NEW',
    growthPrefix: 'Growth',
    level: 'Lv {n}',
    levelUpTitle: 'Level up!',
    levelUpSub: 'Pick one ability · keys 1 2 3',
    evolution: 'Evolution', curse: 'Curse',
    stackOf: '{n}/{m}',
    picksTitle: 'This build',
    shieldBroke: 'Shield saved you!',
    ability: {
      toughBody: { name: 'Tough body', desc: 'Energy builds {a}% slower' },
      quickRecover: { name: 'Quick recovery', desc: 'Energy drains {a}% faster when expanded' },
      cushion: { name: 'Elastic cushion', desc: 'Bounce is {a}% smaller' },
      shockwave: { name: 'Shockwave', desc: 'Releasing above {a}% widens the next gap by +{b}' },
      slideFeet: { name: 'Slick feet', desc: 'Sideways speed +{a}%' },
      shield: { name: 'Shield', desc: 'Survive one wall hit. The wall breaks' },
      foresight: { name: 'Foresight', desc: 'Shows the next {a} gaps above the screen' },
      focus: { name: 'Focus', desc: 'Above {a}% energy, climb speed ×{b}' },
      magnet: { name: 'Magnet', desc: 'Larger orb pickup range' },
      steelLungs: { name: 'Steel lungs', desc: 'Overpressure limit rises to {a}%' },
      reboundBlast: { name: 'Rebound blast', desc: 'Releasing above {a}% breaks the next wall' },
      haste: { name: 'Curse of haste', desc: 'Climb speed +{a}%, orb XP ×{b}' }
    },

    zones: ['Dawn', 'Sky', 'Sunset', 'Night', 'Aurora'],
    speedUp: 'Speed up',
    modeDaily: 'Daily', modeDailyDetail: 'Ghost race',
    dailyBestShort: 'Best {n} m',
    dailyPrefix: 'Daily',
    dailyTitle: 'Daily challenge',
    dailyBonus: 'First daily run +{n} stars',
    attemptN: 'Attempt {n}',
    ghost: 'Ghost',
    // Friend challenge
    challengeSend: 'Challenge a friend', challengeBack: 'Fire back',
    challengeTitle: 'Send a challenge',
    nameLabel: 'Your name (optional)', namePlaceholder: 'Shown to your friend',
    shareMsg: 'I climbed {h} m in Boing! Can you beat me on the same course?',
    shareBtn: 'Send', copyBtn: 'Copy link',
    kakaoBtn: 'Send via KakaoTalk', otherBtn: 'Send with another app',
    kakaoFail: 'Could not open KakaoTalk sharing. Please use another app',
    cardTitleNamed: "{name}'s challenge · {h} m", cardTitle: 'Boing! challenge · {h} m',
    cardDesc: 'Beat me on the same course — 1:1 with my ghost', cardButton: 'Accept',
    copied: 'Link copied', shared: 'Sent', shareFail: 'Could not copy. Long-press to copy manually',
    localWarn: 'This address only works on this PC / Wi-Fi. Host the game on a public https address to send it to friends.',
    incomingTitle: 'Challenge received!',
    incomingFrom: "{name}'s run", incomingFriend: "A friend's run",
    statusVerified: '✓ Verified', statusUnverified: 'Beat this score on the same course!', statusMismatch: '⚠ Score does not match (possibly edited)',
    statusVersion: 'This challenge is from a different version, so the course cannot be rebuilt',
    accept: 'Start duel', later: 'Later',
    badLink: 'This challenge link is not valid',
    win: 'You win!', lose: 'So close — you lost', draw: 'Draw',
    vsLine: 'vs {name} {h} m', vsDiff: '{d} m apart',
    rematch: 'Rematch', vsPrefix: 'Rival',
    nearMissPop: 'Close!', riskyPop: 'Bold!',
    nearMissLabel: 'Close calls',
    missionsTitle: 'Missions', missionDone: 'Mission complete',
    missions: {
      nearMiss: 'Close calls ×{n}', height: 'Reach {n} m in one run', gates: 'Pass {n} gaps', double: 'Clear {n} double gaps',
      long: 'Clear {n} long gaps', risky: 'Release above 85% and survive ×{n}', growthLevel: 'Reach Lv {n} in Growth', runs: 'Play {n} runs'
    },
    skinsTitle: 'Skins',
    coinUnit: 'stars',
    equipped: 'Equipped', equip: 'Equip',
    unlockFor: 'Unlock for {n} stars',
    needMore: '{n} more stars needed',
    earned: '+{n} stars',
    coinsHint: 'Earn 1 star per {p} gaps each run (max {m}). Skins only change looks; collision is identical.',
    unlockBtn: 'Unlock',
    skinNames: { base: 'Jelly', slime: 'Mint slime', orange: 'Orange', watermelon: 'Watermelon', puffer: 'Puffer', fur: 'Fluffball', moon: 'Moon', glass: 'Glass marble', strawberry: 'Strawberry', bee: 'Bee', panda: 'Panda', donut: 'Donut', snow: 'Snowball', lava: 'Lava', galaxy: 'Galaxy', gold: 'Gold' },
    practice: 'Practice',
    tutorial: {
      press: { title: 'Press and release', hint: 'Press anywhere to shrink, let go to bounce. Try it twice.' },
      drag: { title: 'Line up', hint: 'Hold and drag into the glowing zone and stay there briefly.' },
      gate: { title: 'Pass a gap', hint: 'Squeeze before the gap, and let go only once you are fully past it.' },
      energy: { title: 'Handle energy', hint: 'Holding builds energy. Go past {n}%, then let go and watch it drain.' },
      retry: 'Let’s try that again',
      zone: 'Nice!',
      doneTitle: 'All set!',
      doneDetail: 'Now for the real challenge.\nPractice is not recorded.',
      skippedDetail: 'You can replay the tutorial any time from Settings.'
    },

    settingsTitle: 'Settings',
    sfx: 'Sound effects',
    music: 'Music',
    haptics: 'Vibration', hapticsNone: 'This device does not support vibration',
    reducedEffects: 'Reduce effects', reducedEffectsDetail: 'Turns off shake, flashes and particles',
    language: 'Language',
    privacy: 'Privacy',
    privacyBody: 'Records and settings are stored only in this device’s browser. No accounts, ads, analytics or server uploads.',
    close: 'Close',
    on: 'On', off: 'Off'
  };
})(typeof globalThis !== 'undefined' ? globalThis : this);
